#!/usr/bin/env python
#encoding=utf-8

class GraphHandler:
	def addInfluxDB(self):
		import redis, urllib, urllib2

		r = redis.Redis()
		termList = r.zrevrange('CKIP:TERMS:%s' % ('2014-09-09'), 0, 100, True)
		url = 'http://localhost:8086/db/news_seg/series?u=samchien&p=sincos99'
		for i in range(0 ,3):
			req = urllib2.Request(url, '[{"name": "TERM.選舉", "columns":["count", "score"],"points":[[4000, 2000]]}]')
		response = urllib2.urlopen(req)


if __name__ == '__main__':
	gh = GraphHandler()
	gh.addInfluxDB()
